name: Trigger

on:
  schedule:
    # Spustí se každý den ve 3:00 ráno UTC (v ČR ve 4:00 nebo 5:00 podle času)
    - cron: '0 3 * * *'
  # Umožní ti spustit skript kdykoliv ručně tlačítkem "Run workflow" v záložce Actions
  workflow_dispatch: 

jobs:
  generuj-geojson:
    runs-on: ubuntu-latest
    
    # Dává botovi povolení přepsat starý soubor a nahrát nový zpět do repozitáře
    permissions:
      contents: write

    steps:
      - name: Stáhnutí repozitáře
        uses: actions/checkout@v4

      - name: Nastavení prostředí Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalace potřebných knihoven
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Spuštění Python skriptu (tvorba trasy.geojson)
        run: python .github/scripts/pre.py

      - name: Uložení změn a nahrání zpět na web (Push)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add trasy.geojson
          
          # Podmínka zkontroluje, jestli se soubor od včerejška reálně změnil.
          # Pokud ano, provede commit a push. Pokud ne, tiše se ukončí a nespadne.
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizace trasy.geojson 🚌" && git push)
